export const Berlin = () => {
    return (
        <>
            <div className="cover-container">
                <img className="cover" src="/img/berlin/cover.jpg" />
            </div>
            <div className="photo-essay-wrapper">
                <p className="essay-title">Berlin, Germany</p>
                <p className="essay-subtitle">November 23 — December 3, 2023</p>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/walk-1.jpg"
                        data-img-width="4032"
                        data-img-height="3024"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/walk-2.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/walk-3.jpg"
                        data-img-width="2268"
                        data-img-height="4032"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/walk-4.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/walk-5.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="key"
                        src="/img/berlin/hol-1.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/hol-2.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/hol-3.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/hol-4.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/jewish-1.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/jewish-2.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/jewish-3.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/syn-1.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/syn-2.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="key"
                        src="/img/berlin/ham-1.jpg"
                        data-img-width="7952"
                        data-img-height="5304"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/ham-0.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/ham-2.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/ham-3.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/ham-4.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/ham-5.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/ham-6.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/doner-1.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/doner-2.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/doner-3.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                </div>
                <div className="photoset grid-2">
                    <img
                        className="photo"
                        src="/img/berlin/brian.jpg"
                        data-img-width="3024"
                        data-img-height="4032"
                    />
                    <img
                        className="photo"
                        src="/img/berlin/danny.jpg"
                        data-img-width="5304"
                        data-img-height="7952"
                    />
                </div>
                <div className="photoset">
                    <img
                        className="photo"
                        src="/img/berlin/group.jpg"
                        data-img-width="4032"
                        data-img-height="3024"
                    />
                </div>
            </div>
        </>
    )
}
