name: Deploy to Pages

on:
    push:
        branches:
            - master
            - fix-script
    schedule:
        - cron: '0 11 * * 0,1,2,3,4,5,6'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Build
              run: npm install
              working-directory: brianl.am

            - name: Build Notion Data Package
              run: npm install
              working-directory: notion-data

            - name: Fetch Notion Data
              working-directory: notion-data
              env:
                  NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
              run: |
                  echo "NOTION_TOKEN=$NOTION_TOKEN" > .env
                  npm run fetch-status

            - name: Fetch Notion Board Images
              working-directory: notion-data
              env:
                  NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
              run: |
                  echo "NOTION_TOKEN=$NOTION_TOKEN" > .env
                  npm run download-board-img

            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8 #install the python needed
            - name: Install dependencies
              working-directory: queens-image-analysis
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Analyze Notion Board Data
              working-directory: queens-image-analysis
              run: |
                  python analyze.py

            - name: Fetch Notion Board Data
              working-directory: notion-data
              env:
                  NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
              run: |
                  echo "NOTION_TOKEN=$NOTION_TOKEN" > .env
                  npm run upload-boards
